apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-signed-images
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  rules:
  - name: verify-cosign-keyless-signature
    match:
      resources:
        kinds:
        - Pod
    verifyImages:
    - imageReferences:
      - "ghcr.io/cbrkrtek/supply-chain-security-lab*"
      attestors:
      - entries:
        - keyless:
            issuer: "https://token.actions.githubusercontent.com"
            subject: "https://github.com/cbrkrtek/supply-chain-security-lab/.github/workflows/full-pipeline.yml@refs/heads/main"
            rekor:
              url: https://rekor.sigstore.dev
