apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-lab
  namespace: supply-chain-security-lab
spec:
  replicas: 2
  selector:
    matchLabels: {app: security-lab}
  template:
    metadata:
      labels: {app: security-lab}
    spec:
      containers:
      - name: supply-chain-security-lab
        image: ghcr.io/cbrkrtek/supply-chain-security-lab:v0.1.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"

